security:
  oauth2:
    client:
      client-id: web
      client-secret: 123
      scope: all
      grant-type: password
      access-token-uri: http://127.0.0.1:6666/oauth/token
      user-authorization-uri: http://127.0.0.1:6666/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:6666/oauth/token_key